/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f505a42f-c8f9-4d3a-89c9-ed93693c4a08",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_HnEYmwzZI",
    "aws_user_pools_web_client_id": "2aj1bfbl7sn9alhd5r95h4k3gp",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://wd2yaiwd4rhjlpd4okuihyb3ua.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6vwozgeb2veo3iotx6keyi3tuu",
    "aws_user_files_s3_bucket": "amplifyappb9474a62d6c843eea898607b18ce537d192722-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
